// THIS FILE IS GENERATED BY bitmap_generator
typedef struct {
    int bitmap_left, bitmap_top;
    int rows, width, pitch;
    uint8_t *buffer;
} glyph_t;
extern int font_ascender;
extern int font_descender;
extern int font_advance;
extern int font_line_height;
extern glyph_t glyphs[256];
