// THIS FILE IS GENERATED BY bitmap_generator
#include <stdint.h>
typedef struct {
    int bitmap_left, bitmap_top;
    int rows, width, pitch;
    uint8_t *buffer;
} glyph_t;
#define FONT_ASCENDER 13
#define FONT_DESCENDER -3
#define FONT_ADVANCE 8
#define FONT_LINE_HEIGHT 16
extern glyph_t glyphs[256];
