import freetype
import os

directory = os.path.dirname(os.path.abspath(__file__))

SOURCE_PATH = f"{directory}/../../src/kernel/default_font.c"
INCLUDE_PATH = SOURCE_PATH.replace(".c", ".h")
INCLUDE_FILENAME = os.path.basename(INCLUDE_PATH)

face = freetype.Face(f"{directory}/ubuntu-font-family-0.83/UbuntuMono-R.ttf")
face.set_pixel_sizes(0, 16)

class Character:
    bitmap_left: int
    bitmap_top: int
    rows: int
    width: int
    pitch: int
    buffer: list

glyphs = [None] * 256
ascender = face.ascender
descender = face.descender
advance = face.size.max_advance
line_height = face.size.height # Stored in fixed point integer with 6 bits being fraction

for i in range(0x20, 0x100):
    print(chr(i))
    face.load_char(chr(i))
    glyph = face.glyph
    bitmap = glyph.bitmap
    buffer = bitmap.buffer
    if bitmap.width == 0:
        continue
    ch = Character()
    ch.bitmap_left = glyph.bitmap_left
    ch.bitmap_top = glyph.bitmap_top
    ch.rows = bitmap.rows
    ch.width = bitmap.width
    ch.pitch = bitmap.pitch
    ch.buffer = [b for b in buffer]
    glyphs[i] = ch

print(f"advance: {advance}, line_height: {line_height}")

with open(INCLUDE_PATH, "w") as src:
    src.write(
"""// THIS FILE IS GENERATED BY bitmap_generator
typedef struct {
    int bitmap_left, bitmap_top;
    int rows, width, pitch;
    uint8_t *buffer;
} glyph_t;
extern int font_ascender;
extern int font_descender;
extern int font_advance;
extern int font_line_height;
extern glyph_t glyphs[256];
"""
    )

with open(SOURCE_PATH, "w") as src:
    src.write(
f"""// THIS FILE IS GENERATED BY bitmap_generator
#include "{INCLUDE_FILENAME}"
#include <stdint.h>
int font_ascender = {ascender};
int font_descender = {descender};
int font_advance = {advance};
int font_line_height = {line_height};

{"".join([
    f"""static uint8_t glyph_{i}[]={{{",".join([str(b) for b in ch.buffer])}}};\n"""
    for i, ch in enumerate(glyphs) if ch is not None
])}
glyph_t glyphs[256] = {{
    {",".join(["{}" if ch is None else f"""{{
            .bitmap_left = {ch.bitmap_left},
            .bitmap_top = {ch.bitmap_top},
            .width = {ch.width},
            .rows = {ch.rows},
            .pitch = {ch.pitch},
            .buffer = &glyph_{i}
    }}""" for i, ch in enumerate(glyphs)])}
}};
"""
    )
